services:
  app:
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - PROMPTS_USE_FAKE_RESPONSES=false
    image: ghcr.io/dylants/book-prompts:${DOCKER_TAG}
    ports:
      - 3010:3000
